# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:

    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # 2. Configurar Python en el entorno de GitHub Actions
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Usa la versión de Python que necesites

    # 3. Instalar Jupyter para nbconvert
    - name: Install Jupyter and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: List files in root
      run: ls -la

    # Si hay una carpeta relevante, como notebooks, listar su contenido
    - name: List files in 'notebooks' folder (if exists)
      if: ${{ steps.checkout.outputs.dir == 'notebooks' }}
      run: ls -la notebooks/

    # Usar 'find' para listar todos los archivos y carpetas dentro del workspace
    - name: List all files and directories recursively
      run: find . -type f -or -type d
    # 4. Convertir el notebook a Markdown y HTML
    - name: Convertir notebook a Markdown y HTML
      run: |
        jupyter nbconvert --to html "/main/Scrapy_2.ipynb"
    # 5. Subir a GitHub Pages (rama gh-pages)
   # 5. Subir los archivos convertidos al repositorio
    - name: Commit and push changes
      run: |
        git config --global gedar1 "github-actions[bot]"
        git config --global gedar1971@gmail.com "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Convertido notebook a Markdown y HTML en el PR"
        git push origin HEAD:${{ github.head_ref }}  # Push a la rama del PR
